In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading Datas

In [2]:
boston_house = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Boston_Housing/Training_set_boston.csv")

In [3]:
boston_house.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,15.02340,0.0,18.10,0.0,0.6140,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91,12.0
1,0.62739,0.0,8.14,0.0,0.5380,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47,19.9
2,0.03466,35.0,6.06,0.0,0.4379,6.031,23.3,6.6407,1.0,304.0,16.9,362.25,7.83,19.4
3,7.05042,0.0,18.10,0.0,0.6140,6.103,85.1,2.0218,24.0,666.0,20.2,2.52,23.29,13.4
4,0.72580,0.0,8.14,0.0,0.5380,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28,18.2

In [4]:
boston_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 14 columns):
CRIM       404 non-null float64
ZN         404 non-null float64
INDUS      404 non-null float64
CHAS       404 non-null float64
NOX        404 non-null float64
RM         404 non-null float64
AGE        404 non-null float64
DIS        404 non-null float64
RAD        404 non-null float64
TAX        404 non-null float64
PTRATIO    404 non-null float64
B          404 non-null float64
LSTAT      404 non-null float64
MEDV       404 non-null float64
dtypes: float64(14)
memory usage: 44.3 KB

In [5]:
boston_house.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000
mean,3.609125,11.569307,10.985050,0.071782,0.556484,6.315891,68.556436,3.808195,9.356436,404.032178,18.318317,356.278342,12.457351,22.796535
std,8.875058,23.152481,6.894618,0.258447,0.117704,0.709452,27.994922,2.131226,8.589721,166.172655,2.228701,91.566533,7.110381,9.332147
min,0.009060,0.000000,0.740000,0.000000,0.385000,3.863000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081437,0.000000,5.130000,0.000000,0.452000,5.890500,45.550000,2.087875,4.000000,279.000000,16.800000,375.472500,6.772500,16.950000
50%,0.261390,0.000000,8.560000,0.000000,0.538000,6.210000,77.700000,3.175750,5.000000,330.000000,18.700000,391.305000,10.925000,21.600000
75%,3.202962,20.000000,18.100000,0.000000,0.631000,6.636750,93.650000,5.400800,12.000000,666.000000,20.200000,395.755000,16.372500,26.400000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

##### MEDV is the target or dependent variable. And rest are the features or independent variable.

In [6]:
X = boston_house.iloc[:,:-1]
y = boston_house.MEDV

In [7]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,15.02340,0.0,18.10,0.0,0.6140,5.304,97.3,2.1007,24.0,666.0,20.2,349.48,24.91
1,0.62739,0.0,8.14,0.0,0.5380,5.834,56.5,4.4986,4.0,307.0,21.0,395.62,8.47
2,0.03466,35.0,6.06,0.0,0.4379,6.031,23.3,6.6407,1.0,304.0,16.9,362.25,7.83
3,7.05042,0.0,18.10,0.0,0.6140,6.103,85.1,2.0218,24.0,666.0,20.2,2.52,23.29
4,0.72580,0.0,8.14,0.0,0.5380,5.727,69.5,3.7965,4.0,307.0,21.0,390.95,11.28

In [8]:
y

0      12.0
1      19.9
2      19.4
3      13.4
4      18.2
       ...
399    19.5
400    21.1
401    24.5
402    13.4
403    18.6
Name: MEDV, Length: 404, dtype: float64

In [9]:
from sklearn.model_selection import KFold

In [16]:
k = KFold(n_splits=5,random_state=42)

/home/sid/.local/lib/python3.6/site-packages/sklearn/model_selection/_split.py:297: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning

In [17]:
for i, (train_idx,test_idx) in enumerate(k.split(X)):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    print("For fold {}, we have training_data :{} and testing_data:{}".format(i,train_idx,test_idx))

For fold 0, we have training_data :[ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314
 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332
 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350
 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368
 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386
 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403] and testing_data:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80]
For fold 1, we have training_data :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314
 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332
 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350
 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368
 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386
 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403] and testing_data:[ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161]
For fold 2, we have training_data :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314
 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332
 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350
 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368
 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386
 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403] and testing_data:[162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242]
For fold 3, we have training_data :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 324 325 326 327 328 329 330 331 332
 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350
 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368
 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386
 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403] and testing_data:[243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314
 315 316 317 318 319 320 321 322 323]
For fold 4, we have training_data :[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323] and testing_data:[324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403]

In [20]:
n_features = X.shape[1]

In [21]:
n_features

13

In [18]:
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input
from tensorflow.keras import Model

In [19]:
import tensorflow
from numpy.random import seed

In [22]:
data = Input(shape=(n_features,))

hidden = Dense(10,activation="relu")(data)

output = Dense(1)(hidden)

model = Model(inputs = data, outputs=output)

In [23]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 13)]              0
_________________________________________________________________
dense (Dense)                (None, 10)                140
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11
=================================================================
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________

In [29]:
from tensorflow.keras.optimizers import RMSprop

optimizers = RMSprop(0.01)

model.compile(loss="mean_squared_error",optimizer=optimizers)

In [27]:

seed_value = 42
seed(seed_value)        # If you build the model with given parameters, set_random_seed will help you produce the same result on multiple execution


# Recommended by Keras -------------------------------------------------------------------------------------
# 1. Set `PYTHONHASHSEED` environment variable at a fixed value
import os
os.environ['PYTHONHASHSEED']=str(seed_value)

# 2. Set `python` built-in pseudo-random generator at a fixed value
import random
random.seed(seed_value)

# 3. Set `numpy` pseudo-random generator at a fixed value
import numpy as np
np.random.seed(seed_value)
# Recommended by Keras -------------------------------------------------------------------------------------

tensorflow.random.set_seed(seed_value)

In [30]:
val_loss = []
for i, (train_idx,test_idx) in enumerate(k.split(X)):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    
    model.fit(X_train,y_train,epochs=10,batch_size=30,verbose=1)
    
    valloss= model.evaluate(X_test,y_test)
    
    val_loss.append(valloss)
    
print("Final Validation Loss :{}".format(sum(val_loss)/len(val_loss)))

Epoch 1/10
11/11 [==============================] - 0s 3ms/step - loss: 7307.9448
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 266.0879
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 136.8942
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 94.0223
Epoch 5/10
11/11 [==============================] - 0s 1ms/step - loss: 80.6827
Epoch 6/10
11/11 [==============================] - 0s 1ms/step - loss: 114.8695
Epoch 7/10
11/11 [==============================] - 0s 1ms/step - loss: 106.0645
Epoch 8/10
11/11 [==============================] - 0s 1ms/step - loss: 107.5153
Epoch 9/10
11/11 [==============================] - 0s 1ms/step - loss: 117.4737
Epoch 10/10
11/11 [==============================] - 0s 1ms/step - loss: 84.4682
3/3 [==============================] - 0s 1ms/step - loss: 47.1063
Epoch 1/10
11/11 [==============================] - 0s 1ms/step - loss: 84.9782
Epoch 2/10
11/11 [==============================] - 0s 1ms/step - loss: 102.0814
Epoch 3/10
11/11 [==============================] - 0s 1ms/step - loss: 69.4938
Epoch 4/10
11/11 [==============================] - 0s 1ms/step - loss: 89.7650
Epoch 5/10
11/11 [==============================] - 0s 1ms/step - loss: 84.9867
Epoch 6/10
11/11 [==============================] - 0s 1ms/step - loss: 55.9819
Epoch 7/10
11/11 [==============================] - 0s 1ms/step - loss: 85.0014
Epoch 8/10
11/11 [==============================] - 0s 1ms/step - loss: 74.2902
Epoch 9/10
11/11 [==============================] - 0s 1ms/step - loss: 75.5051
Epoch 10/10
11/11 [==============================] - 0s 1ms/step - loss: 69.0118
3/3 [==============================] - 0s 1ms/step - loss: 83.5685
Epoch 1/10
11/11 [==============================] - 0s 1ms/step - loss: 61.0456
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 84.9095
Epoch 3/10
11/11 [==============================] - 0s 1ms/step - loss: 57.0669
Epoch 4/10
11/11 [==============================] - 0s 1ms/step - loss: 54.4835
Epoch 5/10
11/11 [==============================] - 0s 1ms/step - loss: 75.7913
Epoch 6/10
11/11 [==============================] - 0s 1ms/step - loss: 50.2598
Epoch 7/10
11/11 [==============================] - 0s 1ms/step - loss: 61.5890
Epoch 8/10
11/11 [==============================] - 0s 1ms/step - loss: 62.8001
Epoch 9/10
11/11 [==============================] - 0s 1ms/step - loss: 72.0487
Epoch 10/10
11/11 [==============================] - 0s 1ms/step - loss: 52.8503
3/3 [==============================] - 0s 1ms/step - loss: 99.4929
Epoch 1/10
11/11 [==============================] - 0s 1ms/step - loss: 53.8841
Epoch 2/10
11/11 [==============================] - 0s 1ms/step - loss: 60.5917
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 40.8983
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 53.1965
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 43.5504
Epoch 6/10
11/11 [==============================] - 0s 1ms/step - loss: 53.4164
Epoch 7/10
11/11 [==============================] - 0s 1ms/step - loss: 52.1819
Epoch 8/10
11/11 [==============================] - 0s 1ms/step - loss: 39.9990
Epoch 9/10
11/11 [==============================] - 0s 1ms/step - loss: 50.8898
Epoch 10/10
11/11 [==============================] - 0s 1ms/step - loss: 43.9660
3/3 [==============================] - 0s 1ms/step - loss: 41.6045
Epoch 1/10
11/11 [==============================] - 0s 1ms/step - loss: 48.1529
Epoch 2/10
11/11 [==============================] - 0s 1ms/step - loss: 48.7180
Epoch 3/10
11/11 [==============================] - 0s 1ms/step - loss: 41.8695
Epoch 4/10
11/11 [==============================] - 0s 1ms/step - loss: 44.8433
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 38.0595
Epoch 6/10
11/11 [==============================] - 0s 1ms/step - loss: 48.3215
Epoch 7/10
11/11 [==============================] - 0s 963us/step - loss: 42.5437
Epoch 8/10
11/11 [==============================] - 0s 1ms/step - loss: 37.5941
Epoch 9/10
11/11 [==============================] - 0s 1ms/step - loss: 47.3559
Epoch 10/10
11/11 [==============================] - 0s 1ms/step - loss: 43.4116
3/3 [==============================] - 0s 873us/step - loss: 64.9027
Final Validation Loss :67.33496475219727

### Hyperparameters tuning

Most machine learning problems require a lot of hyperparameter tuning. Unfortunately, we can't provide concrete tuning rules for every model. Lowering the learning rate can help one model converge efficiently but make another model converge much too slowly. You must experiment to find the best set of hyperparameters for your dataset. That said, here are a few rules of thumb:

Training loss should steadily decrease, steeply at first, and then more slowly until the slope of the curve reaches or approaches zero.

If the training loss does not converge, train for more epochs.

If the training loss decreases too slowly, increase the learning rate. Note that setting the learning rate too high may also prevent training loss from converging.

If the training loss varies wildly (that is, the training loss jumps around), decrease the learning rate.

Lowering the learning rate while increasing the number of epochs or the batch size is often a good combination.

Setting the batch size to a very small batch number can also cause instability. First, try large batch size values. Then, decrease the batch size until you see degradation.

For real-world datasets consisting of a very large number of examples, the entire dataset might not fit into memory. In such cases, you'll need to reduce the batch size to enable a batch to fit into memory.
Remember: the ideal combination of hyperparameters is data dependent, so you must always experiment and verify.

### It can be done with 1. Sklearn and 2. Keras

#### Sklearn

We cann't use native sklearn as model is defined by keras. So, we must integrate keras and sklearn properly.

So, we first create function which allows us to create model in our old keras way.

Then, we define KerasRegressor model which is an sklearn api for keras.

In [31]:
from keras.wrappers.scikit_learn import KerasRegressor

In [58]:
def create_model(optimizers=RMSprop(0.01)):
    inp = Input(shape=(n_features,))
    
    hid = Dense(10,activation="relu")(inp)
    
    hid = Dense(8,activation="relu")(hid)
    
    out = Dense(1)(hid)
    
    model = Model(inputs=inp, outputs= out)
    
    model.compile(loss="mean_squared_error",metrics=['mse'],optimizer=optimizers)
    
    return model

In [59]:
model = KerasRegressor(build_fn=create_model,verbose=1)

In [60]:
batch_size = [10,20,30,40,50]

epochs=[10,20,50]

params_grid = {'batch_size':batch_size,'epochs':epochs}

In [61]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [62]:
X_tra,X_tes,y_tra,y_tes = train_test_split(X,y,test_size=0.2,random_state=43)